export const SIGN_IN="SIGN_IN";
export const SIGN_OUT="SIGN_OUT";
export const FETCH_PRODUCT="FETCH_PRODUCT"
export const FETCH_PRODUCTS="FETCH_PRODUCTS"
export const EDIT_PRODUCT="EDIT_PRODUCT"
export const DELETE_PRODUCT="DELETE_PRODUCT"
export const PRODUCT_LOADING="PRODUCT_LOADING"
export const PRODUCT_FAILED='PRODUCT_FAILED'